INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Acre', 'AC');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Alagoas', 'AL');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Amazonas', 'AM');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Amapá', 'AP');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Bahia', 'BA');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Ceará', 'CE');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Distrito Federal', 'DF');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Espírito Santo', 'ES');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Goiás', 'GO');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Maranhão', 'MA');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Minas Gerais', 'MG');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Mato Grosso do Sul', 'MS');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Mato Grosso', 'MT');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Pará', 'PA');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Paraíba', 'PB');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Pernambuco', 'PE');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Piauí', 'PI');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Paraná', 'PR');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Rio de Janeiro', 'RJ');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Rio Grande do Norte', 'RN');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Rondônia', 'RO');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Roraima', 'RR');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Rio Grande do Sul', 'RS');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Santa Catarina', 'SC');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Sergipe', 'SE');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('São Paulo', 'SP');
INSERT INTO `drogaria_db`.`Estado` (`nome`, `sigla`) VALUES('Tocantins', 'TO');
